-- PostgreSQL Production Database Schema for Futurrizon Technologies Pvt Ltd
-- Domain Architecture: SaaS & Enterprise Software Operations Platform (custom)
-- Generated by BizzMitra AI Engine
-- Problem Statement Reference:
-- "Futurrizon works with businesses that use multiple digital tools such as Microsoft 365, SharePoint, Power Platform, CRM systems, Excel and other business applications. However, business information can remain fragmented across these systems, creating manual data entry, duplicate information, disconnected workflows and delays in reporting.  Employees may have to move information manually between systems, follow up on approvals, search across multiple locations for the latest information, and prepare reports from different data sources. This makes business processes slower and makes it difficult for management to get timely and reliable insights.  We want to build an AI-powered solution that connects existing business systems, identifies fragmented data and workflow bottlenecks, automates repetitive tasks, and provides a unified view of business operations without requiring companies to replace their existing software."

CREATE TABLE IF NOT EXISTS public.custom_records (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  col1_data TEXT NOT NULL, -- Semantic Mapping: Operational Category
  col2_data TEXT NOT NULL, -- Semantic Mapping: Parameters & Scope
  status TEXT NOT NULL,    -- Semantic Mapping: Execution Stage
  badge TEXT DEFAULT 'Active',
  assignee TEXT NOT NULL,  -- Semantic Mapping: Assigned Lead
  metric_value TEXT NOT NULL, -- Semantic Mapping: SLA Turnaround
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.custom_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.custom_records
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Team and Role Authentication table
CREATE TABLE IF NOT EXISTS public.custom_users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  badge TEXT NOT NULL,
  department TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.custom_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read-write for authenticated users"
  ON public.custom_users
  FOR ALL
  USING (true)
  WITH CHECK (true);
